version: 2.0
jobs:
 test-workflow:
   docker:
     - image: alpine:3.7
   steps:
     - run:
          command: |
            echo "${Value1}"
            
workflows:
 version: 2
  test-workflow:
    jobs:
      - test:
        context: KANKYO_HENSU_MEI
