version: 2
jobs:
  build1:
    docker: # 各ジョブで Executor (docker、macos、または machine)
    # を指定する必要があります。これらの比較や他の例
    # については、circleci.com/docs/ja/2.0/executor-types/
    # を参照してください。
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout
      - save_cache: # 環境変数のキャッシュキーテンプレートを
      # 使用して、依存関係をキャッシュします。
      # circleci.com/docs/ja/2.0/caching/ を参照してください。
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-demo-workflows

  build2:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - restore_cache: # キャッシュされた依存関係を復元します。
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
