version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

jobs:
  my-job:
    executor: my-executor
    steps:
      - setup_remote_docker
      - run:
          name: contextで設定した値を表示する
          command: |
            echo "${DOCKERHUB_PASSWORD}"

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - my-job