version: 2.1

jobs:
  sayhello: # パラメーター化されたジョブを定義します
    description: パラメーター化されたジョブを例示する以外、ほとんど何もしないジョブ
    parameters:
      saywhat:
        description: "だれに挨拶するべきか"
        default: "World"
        type: string
    machine: true
    steps:

      - run: echo "Hello << parameters.saywhat >>"

workflows:
  build:
    jobs:

      - sayhello: # パラメーター化したジョブを呼び出します
          saywhat: Everyone