version: 2.1
jobs:
  docker:
    - image: alpine:3.7
  commands:
    sayhello:
      description: "デモ用のごく簡単なコマンドです"
      parameters:
        to:
          type: string
          default: "Hello World"
      steps:
        - run: echo << parameters.to >>




