version: 2.1


jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: 
          name: "echo an env var that is part of our context"
          command:
            echo KANKYO_HENSU_MEI
  job:
    run-tests:
      docker:
        - image: circleci/ruby:2.4.1
      steps:
        - checkout
        - run: echo "${KANKYO_HENSU_MEI}"
    
workflows:
  version: 2
  my-workflow:
    jobs:
      - run-tests:
        context: SAMPLE
