version: 2.0
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: 最初の一歩
          command: |
            echo 'Hello World!'
            echo 'This is the deliverly pipeline'
      - run:
          name: コードの取得
          command: |
            cd test
            ls -al
            echo '^^^That shoud look familiar^^^'
