deploy:
    working_directory: ~/workspace
    docker:
      - image: node:9.4.0
    steps:
      - attach_workspace:
          at: .
      - deploy:
          command: echo Deploy!

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master