version: 2.1




jobs:
 build:
   docker:
     # ここでは、DLC は何もしません。キャッシュの状況は、イメージレイヤーにどれだけ共通点があるかによって左右されます。
     - image: circleci/node:9.8.0-stretch-browsers
   steps:
     - checkout
     - setup_remote_docker:
         docker_layer_caching: true
     # ここでは、DLC はレイヤーを明示的にキャッシュし、リビルドを避けようとします。
     - run: docker build .