version: 2.1


commands:
  sayhello:
    description: "デモ用のごく簡単なコマンドです"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>

executors:
  my-executor:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

jobs:
  my-job:
    executor: my-executor
    steps:
      - run:
          name: contextで設定した値を表示する
          command:
            echo "${KANKYO_HENSU_MEI}"

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - my-job
          context: SAMPLE