version: 2
jobs:
  build:
    docker: # Executor タイプです。他に machine、macOS という実行タイプを指定できます
      - image: circleci/node:4.8.2 # プライマリコンテナです。このなかでジョブコマンドが実行されます
    steps:
      - checkout # ソースコードをチェックアウトする特別なステップ
      - run: # コマンドを実行する run ステップ。以下を参照してください。
      # circleci.com/docs/ja/2.0/configuration-reference/#run
          name: テストを実行
          command: make test # 実行可能なコマンド。デフォルトでは、
          # /bin/bash -eo pipefail オプションを使用して
          # 非ログインシェルで実行されます。

