version: 2.1


jobs:
  build:
    steps:
      - checkout
      - run: 
          name: "echo an env var that is part of our context"
          command:
            echo $KANKYO_HENSU_MEI

workflows:
  test-env-vars:
    jobs:
      - build:
          context: SAMPLE # has an env var called MY_ENV_VAR
