version: 2.0
jobs:
  - run:
      name: contextで設定した値を表示する
      command: |
        echo KANKYO_HENSU_MEI



workflows:
  version: 2
  build_and_push_image:
    jobs:
      - test:
          context: KANKYO_HENSU_MEI

