version: 2.0
jobs:
  - run:
      name: contextで設定した値を表示する
      command: |
        echo "${Value1}"
        echo "${Value2}"            

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
        context: KANKYO_HENSU_MEI
